In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://www.formula1.com/en/results/2025/races"
data = requests.get(url)
soup = BeautifulSoup(data.content, 'html.parser')
races_table = soup.select('table.f1-table')[0]
links = races_table.find_all('a', href=True)
links = [l.get("href") for l in links]
links = [l for l in links if '/2025/' in l]

In [3]:
links

['/../../en/results/2025/races/1254/australia/race-result',
 '/../../en/results/2025/races/1255/china/race-result',
 '/../../en/results/2025/races/1256/japan/race-result',
 '/../../en/results/2025/races/1257/bahrain/race-result',
 '/../../en/results/2025/races/1258/saudi-arabia/race-result',
 '/../../en/results/2025/races/1259/miami/race-result',
 '/../../en/results/2025/races/1260/emilia-romagna/race-result',
 '/../../en/results/2025/races/1261/monaco/race-result',
 '/../../en/results/2025/races/1262/spain/race-result',
 '/../../en/results/2025/races/1263/canada/race-result',
 '/../../en/results/2025/races/1264/austria/race-result',
 '/../../en/results/2025/races/1277/great-britain/race-result',
 '/../../en/results/2025/races/1265/belgium/race-result']

In [4]:
race_urls = [f"https://formula1.com{l}" for l in links]

In [5]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
races = pd.read_html(str(races_table))[0]
races

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Flag of AustraliaAustralia,16 Mar,Lando NorrisNOR,McLaren,57,1:42:06.304
1,Flag of People’s Republic of ChinaChina,23 Mar,Oscar PiastriPIA,McLaren,56,1:30:55.026
2,Flag of JapanJapan,06 Apr,Max VerstappenVER,Red Bull Racing,53,1:22:06.983
3,Flag of BahrainBahrain,13 Apr,Oscar PiastriPIA,McLaren,57,1:35:39.435
4,Flag of Saudi ArabiaSaudi Arabia,20 Apr,Oscar PiastriPIA,McLaren,50,1:21:06.758
5,Flag of United States of AmericaMiami,04 May,Oscar PiastriPIA,McLaren,57,1:28:51.587
6,Flag of ItalyEmilia-Romagna,18 May,Max VerstappenVER,Red Bull Racing,63,1:31:33.199
7,Flag of MonacoMonaco,25 May,Lando NorrisNOR,McLaren,78,1:40:33.843
8,Flag of SpainSpain,01 Jun,Oscar PiastriPIA,McLaren,66,1:32:57.375
9,Flag of CanadaCanada,15 Jun,George RussellRUS,Mercedes,70,1:31:52.688
10,Flag of AustriaAustria,29 Jun,Lando NorrisNOR,McLaren,70,1:23:47.693
11,Flag of Great BritainGreat Britain,06 Jul,Lando NorrisNOR,McLaren,52,1:37:15.735
12,Flag of BelgiumBelgium,27 Jul,Oscar PiastriPIA,McLaren,44,1:25:22.601

In [6]:
races = races.iloc[: -2]

In [7]:
gp_rename = {
    'Flag of AustraliaAustralia': 'Australian Grand Prix',
    'Flag of People’s Republic of ChinaChina': 'Chinese Grand Prix',
    'Flag of MonacoMonaco': 'Monaco Grand Prix',
    'Flag of CanadaCanada': 'Canadian Grand Prix',
    'Flag of AustriaAustria': 'Austrian Grand Prix',
    'Flag of JapanJapan': 'Japanese Grand Prix',
    'Flag of BahrainBahrain': 'Bahrain Grand Prix',
    'Flag of Saudi ArabiaSaudi Arabia': 'Saudi Arabian Grand Prix',
    'Flag of United States of AmericaMiami': 'Miami Grand Prix',
    'Flag of ItalyEmilia-Romagna': 'Emilia Romagna Grand Prix',
    'Flag of SpainSpain': 'Spanish Grand Prix',
}

races['GRAND PRIX'] = races['GRAND PRIX'].replace(gp_rename)
races

/var/folders/3s/qxkngbts3cqdwpx4jy3l2wxr0000gp/T/ipykernel_72658/3837458854.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  races['GRAND PRIX'] = races['GRAND PRIX'].replace(gp_rename)

,GRAND PRIX,DATE,WINNER,TEAM,LAPS,TIME
0,Australian Grand Prix,16 Mar,Lando NorrisNOR,McLaren,57,1:42:06.304
1,Chinese Grand Prix,23 Mar,Oscar PiastriPIA,McLaren,56,1:30:55.026
2,Japanese Grand Prix,06 Apr,Max VerstappenVER,Red Bull Racing,53,1:22:06.983
3,Bahrain Grand Prix,13 Apr,Oscar PiastriPIA,McLaren,57,1:35:39.435
4,Saudi Arabian Grand Prix,20 Apr,Oscar PiastriPIA,McLaren,50,1:21:06.758
5,Miami Grand Prix,04 May,Oscar PiastriPIA,McLaren,57,1:28:51.587
6,Emilia Romagna Grand Prix,18 May,Max VerstappenVER,Red Bull Racing,63,1:31:33.199
7,Monaco Grand Prix,25 May,Lando NorrisNOR,McLaren,78,1:40:33.843
8,Spanish Grand Prix,01 Jun,Oscar PiastriPIA,McLaren,66,1:32:57.375
9,Canadian Grand Prix,15 Jun,George RussellRUS,Mercedes,70,1:31:52.688
10,Austrian Grand Prix,29 Jun,Lando NorrisNOR,McLaren,70,1:23:47.693

In [8]:
races['DATE'] = races['DATE'].apply(lambda x: f"{x} 2025")
races['DATE'] = pd.to_datetime(races['DATE'], format='%d %b %Y')
races.drop(columns=['WINNER', 'TEAM', 'LAPS', 'TIME'], inplace=True)
races

/var/folders/3s/qxkngbts3cqdwpx4jy3l2wxr0000gp/T/ipykernel_72658/4162438778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  races['DATE'] = races['DATE'].apply(lambda x: f"{x} 2025")
/var/folders/3s/qxkngbts3cqdwpx4jy3l2wxr0000gp/T/ipykernel_72658/4162438778.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  races['DATE'] = pd.to_datetime(races['DATE'], format='%d %b %Y')
/var/folders/3s/qxkngbts3cqdwpx4jy3l2wxr0000gp/T/ipykernel_72658/4162438778.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  races.drop(columns=['WINNER', 'TEAM', 'LAPS', 'TIME'], inplace=True)

                   GRAND PRIX       DATE
0       Australian Grand Prix 2025-03-16
1          Chinese Grand Prix 2025-03-23
2         Japanese Grand Prix 2025-04-06
3          Bahrain Grand Prix 2025-04-13
4    Saudi Arabian Grand Prix 2025-04-20
5            Miami Grand Prix 2025-05-04
6   Emilia Romagna Grand Prix 2025-05-18
7           Monaco Grand Prix 2025-05-25
8          Spanish Grand Prix 2025-06-01
9         Canadian Grand Prix 2025-06-15
10        Austrian Grand Prix 2025-06-29

In [9]:
race_result_urls = race_urls

In [10]:
race_quali_urls = [url.replace('race-result', 'qualifying') for url in race_urls]
race_quali_urls = race_quali_urls[: -2]
race_result_urls = race_result_urls[: -2]

In [11]:
print(race_quali_urls[-1]), print(race_result_urls[-1])

https://formula1.com/../../en/results/2025/races/1264/austria/qualifying
https://formula1.com/../../en/results/2025/races/1264/austria/race-result

(None, None)

In [16]:
results = []
for url in race_result_urls:
    data = requests.get(url)
    soup = BeautifulSoup(data.content, 'html.parser')
    results_table = soup.select('table.f1-table')[0]
    res = pd.read_html(str(results_table))[0]
    results.append(res)
results = pd.concat(results, ignore_index=True)

In [ ]:
results.reset_index
results.drop(['PTS.', 'NO.', 'LAPS'])
res_rename = {
    'Lando NorrisNOR': 'norris',
    'Max VerstappenVER': 'max_verstappen',
    'George RussellRUS': 'russel',
    'Flag of CanadaCanada': 'Canadian Grand Prix',
    'Flag of AustriaAustria': 'Austrian Grand Prix',
    'Flag of JapanJapan': 'Japanese Grand Prix',
    'Flag of BahrainBahrain': 'Bahrain Grand Prix',
    'Flag of Saudi ArabiaSaudi Arabia': 'Saudi Arabian Grand Prix',
    'Flag of United States of AmericaMiami': 'Miami Grand Prix',
    'Flag of ItalyEmilia-Romagna': 'Emilia Romagna Grand Prix',
    'Flag of SpainSpain': 'Spanish Grand Prix',
}
results['DRIVER'] = results['DRIVER'].replace(res_rename)
results

,POS.,NO.,DRIVER,TEAM,LAPS,TIME / RETIRED,PTS.
0,1,4,Lando NorrisNOR,McLaren,57,1:42:06.304,25
1,2,1,Max VerstappenVER,Red Bull Racing,57,+0.895s,18
2,3,63,George RussellRUS,Mercedes,57,+8.481s,15
3,4,12,Kimi AntonelliANT,Mercedes,57,+10.135s,12
4,5,23,Alexander AlbonALB,Williams,57,+12.773s,10
...,...,...,...,...,...,...,...
221,NC,23,Alexander AlbonALB,Williams,15,DNF,0
222,NC,1,Max VerstappenVER,Red Bull Racing,0,DNF,0
223,NC,12,Kimi AntonelliANT,Mercedes,0,DNF,0
224,NC,55,Carlos SainzSAI,Williams,0,DNS,0
225,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...,Note - Colapinto received a five-second time p...