In [1]:
from fastf1 import get_event
import pandas as pd

aus_gp_2025 = get_event(2025, 'Australian Grand Prix')

aus_gp_2025

req         WARNING 	DEFAULT CACHE ENABLED! (1.14 GB) /Users/ehteshaam/Library/Caches/fastf1

RoundNumber                                                          1
Country                                                      Australia
Location                                                     Melbourne
OfficialEventName    FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...
EventDate                                          2025-03-16 00:00:00
EventName                                        Australian Grand Prix
EventFormat                                               conventional
Session1                                                    Practice 1
Session1Date                                 2025-03-14 12:30:00+11:00
Session1DateUtc                                    2025-03-14 01:30:00
Session2                                                    Practice 2
Session2Date                                 2025-03-14 16:00:00+11:00
Session2DateUtc                                    2025-03-14 05:00:00
Session3                                                    Practice 3
Session3Date                                 2025-03-15 12:30:00+11:00
Session3DateUtc                                    2025-03-15 01:30:00
Session4                                                    Qualifying
Session4Date                                 2025-03-15 16:00:00+11:00
Session4DateUtc                                    2025-03-15 05:00:00
Session5                                                          Race
Session5Date                                 2025-03-16 15:00:00+11:00
Session5DateUtc                                    2025-03-16 04:00:00
F1ApiSupport                                                      True
Name: 1, dtype: object

In [2]:
import fastf1
from fastf1 import plotting
import pandas as pd
gp = get_event(2025, 1)
gpr = fastf1.get_session(2025, 1, 'R')
gpr.load()
results = gpr.results
results['GP name'] = gp['OfficialEventName']
results['country'] = gp['Country']
results['location'] = gp['Location']
results = results[['DriverId', 'TeamName', 'GridPosition', 'Position','Status']]
results.reset_index(drop=True)
results

core           INFO 	Loading data for Australian Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

          DriverId         TeamName  GridPosition  Position    Status
4           norris          McLaren           1.0       1.0  Finished
1   max_verstappen  Red Bull Racing           3.0       2.0  Finished
63         russell         Mercedes           4.0       3.0  Finished
12       antonelli         Mercedes          16.0       4.0  Finished
23           albon         Williams           6.0       5.0  Finished
18          stroll     Aston Martin          13.0       6.0  Finished
27      hulkenberg      Kick Sauber          17.0       7.0  Finished
16         leclerc          Ferrari           7.0       8.0  Finished
81         piastri          McLaren           2.0       9.0  Finished
44        hamilton          Ferrari           8.0      10.0  Finished
10           gasly           Alpine           9.0      11.0  Finished
22         tsunoda     Racing Bulls           5.0      12.0  Finished
31            ocon     Haas F1 Team          19.0      13.0  Finished
87         bearman     Haas F1 Team          20.0      14.0  Finished
30          lawson  Red Bull Racing          18.0      15.0   Retired
5        bortoleto      Kick Sauber          15.0      16.0   Retired
14          alonso     Aston Martin          12.0      17.0   Retired
55           sainz         Williams          10.0      18.0   Retired
7           doohan           Alpine          14.0      19.0   Retired
6           hadjar     Racing Bulls          11.0      20.0   Retired

In [3]:
results.dtypes

DriverId         object
TeamName         object
GridPosition    float64
Position        float64
Status           object
dtype: object

In [4]:
season2025 = []

for race in range(1, 12):
    
    gp = fastf1.get_event(2025, race)
    
    gpr = fastf1.get_session(2025, race, 'R')
    gpr.load()

    results = gpr.results.copy()

    results['GP name']  = gp['OfficialEventName']
    results['country']  = gp['Country']
    results['location'] = gp['Location']
    results['date'] = gp['EventDate']

    keep = ['GP name', 'date', 'DriverId', 'TeamName', 'GridPosition', 'Position', 'Status', 'country', 'location']
    results = results[keep].reset_index(drop=True)

    season2025.append(results)

season2025 = pd.concat(season2025, ignore_index=True)
season2025

core           INFO 	Loading data for Australian Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.6.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']

,GP name,date,DriverId,TeamName,GridPosition,Position,Status,country,location
0,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,norris,McLaren,1.0,1.0,Finished,Australia,Melbourne
1,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,max_verstappen,Red Bull Racing,3.0,2.0,Finished,Australia,Melbourne
2,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,russell,Mercedes,4.0,3.0,Finished,Australia,Melbourne
3,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,antonelli,Mercedes,16.0,4.0,Finished,Australia,Melbourne
4,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,albon,Williams,6.0,5.0,Finished,Australia,Melbourne
...,...,...,...,...,...,...,...,...,...
214,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,tsunoda,Red Bull Racing,18.0,16.0,Lapped,Austria,Spielberg
215,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,albon,Williams,12.0,17.0,Retired,Austria,Spielberg
216,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,max_verstappen,Red Bull Racing,7.0,18.0,Retired,Austria,Spielberg
217,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,antonelli,Mercedes,9.0,19.0,Retired,Austria,Spielberg
218,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,sainz,Williams,19.0,20.0,Did not start,Austria,Spielberg

In [5]:
season2025['Status'].unique()

array(['Finished', 'Retired', 'Lapped', 'Disqualified', 'Did not start'],
      dtype=object)

In [6]:
season2025 = season2025.rename(columns={'DriverId': 'driverRef'})

In [7]:
season2025

,GP name,date,driverRef,TeamName,GridPosition,Position,Status,country,location
0,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,norris,McLaren,1.0,1.0,Finished,Australia,Melbourne
1,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,max_verstappen,Red Bull Racing,3.0,2.0,Finished,Australia,Melbourne
2,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,russell,Mercedes,4.0,3.0,Finished,Australia,Melbourne
3,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,antonelli,Mercedes,16.0,4.0,Finished,Australia,Melbourne
4,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,albon,Williams,6.0,5.0,Finished,Australia,Melbourne
...,...,...,...,...,...,...,...,...,...
214,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,tsunoda,Red Bull Racing,18.0,16.0,Lapped,Austria,Spielberg
215,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,albon,Williams,12.0,17.0,Retired,Austria,Spielberg
216,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,max_verstappen,Red Bull Racing,7.0,18.0,Retired,Austria,Spielberg
217,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,antonelli,Mercedes,9.0,19.0,Retired,Austria,Spielberg
218,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,sainz,Williams,19.0,20.0,Did not start,Austria,Spielberg

In [8]:
drivers = pd.read_csv('./datasets/drivers.csv')
circuits = pd.read_csv('./datasets/circuits.csv')
constructors = pd.read_csv('./datasets/constructors.csv')
season2025 = season2025.rename(columns={
    'GridPosition': 'start',
    'Position': 'finish',
    'TeamName':'team',
})
constructors = constructors.rename(columns={
    'name': 'team',
})

In [9]:
season2025['start'] = season2025['start'].astype('Int64')
season2025['finish'] = season2025['finish'].astype('Int64')

In [10]:
gp_map = {
    r'.*AUSTRALIAN.*': 'Australian Grand Prix',
    r'.*CHINESE.*': 'Chinese Grand Prix',
    r'.*JAPANESE.*': 'Japanese Grand Prix',
    r'.*BAHRAIN.*': 'Bahrain Grand Prix',
    r'.*SAUDI.*': 'Saudi Arabian Grand Prix',
    r'.*MIAMI.*': 'Miami Grand Prix',
    r'.*EMILIA.*': 'Emilia-Romagna Grand Prix',
    r'.*MONACO.*': 'Monaco Grand Prix',
    r'.*SPAIN.*': 'Spanish Grand Prix',
    r'.*CANADA.*': 'Canadian Grand Prix',
    r'.*AUSTRIA.*': 'Austrian Grand Prix'
}
team_map = {
    'Red Bull Racing': 'Red Bull',
    'Kick Sauber': 'Sauber',
    'Racing Bulls': 'RB F1 Team'
}
season2025['team'] = season2025['team'].replace(team_map)
season2025['GP name'] = season2025['GP name'].replace(gp_map, regex=True)

In [11]:
season2025 = season2025.merge(
    drivers[['driverRef', 'dob', 'nationality']],
    on='driverRef',
    how='left'
)
season2025 = season2025.merge(
    circuits[['location', 'name']],
    on='location',
    how='left'
)
season2025 = season2025.merge(
    constructors[['team','nationality']],
    on='team',
    how='left'
)
season2025

,GP name,date,driverRef,team,start,finish,Status,country,location,dob,nationality_x,name,nationality_y
0,Australian Grand Prix,2025-03-16,norris,McLaren,1,1,Finished,Australia,Melbourne,1999-11-13,British,Albert Park Grand Prix Circuit,British
1,Australian Grand Prix,2025-03-16,max_verstappen,Red Bull,3,2,Finished,Australia,Melbourne,1997-09-30,Dutch,Albert Park Grand Prix Circuit,Austrian
2,Australian Grand Prix,2025-03-16,russell,Mercedes,4,3,Finished,Australia,Melbourne,1998-02-15,British,Albert Park Grand Prix Circuit,German
3,Australian Grand Prix,2025-03-16,antonelli,Mercedes,16,4,Finished,Australia,Melbourne,NaN,NaN,Albert Park Grand Prix Circuit,German
4,Australian Grand Prix,2025-03-16,albon,Williams,6,5,Finished,Australia,Melbourne,1996-03-23,Thai,Albert Park Grand Prix Circuit,British
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Austrian Grand Prix,2025-06-29,tsunoda,Red Bull,18,16,Lapped,Austria,Spielberg,2000-05-11,Japanese,Red Bull Ring,Austrian
234,Austrian Grand Prix,2025-06-29,albon,Williams,12,17,Retired,Austria,Spielberg,1996-03-23,Thai,Red Bull Ring,British
235,Austrian Grand Prix,2025-06-29,max_verstappen,Red Bull,7,18,Retired,Austria,Spielberg,1997-09-30,Dutch,Red Bull Ring,Austrian
236,Austrian Grand Prix,2025-06-29,antonelli,Mercedes,9,19,Retired,Austria,Spielberg,NaN,NaN,Red Bull Ring,German
237,Austrian Grand Prix,2025-06-29,sainz,Williams,19,20,Did not start,Austria,Spielberg,1994-09-01,Spanish,Red Bull Ring,British

In [12]:
season2025.dtypes

GP name                  object
date             datetime64[ns]
driverRef                object
team                     object
start                     Int64
finish                    Int64
Status                   object
country                  object
location                 object
dob                      object
nationality_x            object
name                       None
nationality_y            object
dtype: object

In [13]:
season2025['dob'] = pd.to_datetime(season2025['dob'], errors='coerce')
season2025['statusId'] = season2025['Status'].apply(
    lambda s: 1 if s in {'Finished', 'Lapped', 'Disqualified'} else 3
)
season2025['year'] = 2025

season2025 = season2025.reset_index(drop=True)
season2025 = season2025.rename(columns={
    'name': 'circuit name',
    'nationality_x':'driver_home',
    'nationality_y':'team_home'
})

final_cols = [
    'year', 'GP name', 'date', 'start', 'finish', 'statusId',
    'team', 'driverRef', 'dob', 'circuit name', 'location', 'country', 'driver_home', 'team_home'
]
season2025 = season2025[final_cols]

season2025

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver_home,team_home
0,2025,Australian Grand Prix,2025-03-16,1,1,1,McLaren,norris,1999-11-13,Albert Park Grand Prix Circuit,Melbourne,Australia,British,British
1,2025,Australian Grand Prix,2025-03-16,3,2,1,Red Bull,max_verstappen,1997-09-30,Albert Park Grand Prix Circuit,Melbourne,Australia,Dutch,Austrian
2,2025,Australian Grand Prix,2025-03-16,4,3,1,Mercedes,russell,1998-02-15,Albert Park Grand Prix Circuit,Melbourne,Australia,British,German
3,2025,Australian Grand Prix,2025-03-16,16,4,1,Mercedes,antonelli,NaT,Albert Park Grand Prix Circuit,Melbourne,Australia,NaN,German
4,2025,Australian Grand Prix,2025-03-16,6,5,1,Williams,albon,1996-03-23,Albert Park Grand Prix Circuit,Melbourne,Australia,Thai,British
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,2025,Austrian Grand Prix,2025-06-29,18,16,1,Red Bull,tsunoda,2000-05-11,Red Bull Ring,Spielberg,Austria,Japanese,Austrian
234,2025,Austrian Grand Prix,2025-06-29,12,17,3,Williams,albon,1996-03-23,Red Bull Ring,Spielberg,Austria,Thai,British
235,2025,Austrian Grand Prix,2025-06-29,7,18,3,Red Bull,max_verstappen,1997-09-30,Red Bull Ring,Spielberg,Austria,Dutch,Austrian
236,2025,Austrian Grand Prix,2025-06-29,9,19,3,Mercedes,antonelli,NaT,Red Bull Ring,Spielberg,Austria,NaN,German
237,2025,Austrian Grand Prix,2025-06-29,19,20,3,Williams,sainz,1994-09-01,Red Bull Ring,Spielberg,Austria,Spanish,British

In [14]:
def nationality(x):
    x = str(x).strip().lower()
    if x in ['austrian', 'austria']:
        return 'AUT'
    if x in ['australian', 'australia']:
        return 'AUS'
    if x in ['indian', 'india']:
        return 'IND'
    if x in ['indonesian', 'indonesia']:
        return 'INA'
    if x in ['uk', 'british', 'england', 'great britain']:
        return 'BRI'
    if x in ['usa', 'united states', 'american']:
        return 'AME'
    if x in ['fra', 'france', 'french']:
        return 'FRE'
    return x[:3].upper()

season2025['driver_home'] = season2025['driver_home'].apply(nationality)
season2025['team_home'] = season2025['team_home'].apply(nationality)
season2025['country'] = season2025['country'].apply(nationality)

season2025['driver home'] = (season2025['driver_home'] == season2025['country']).astype(int)
season2025['team home'] = (season2025['team_home'] == season2025['country']).astype(int)

In [15]:
season2025

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver_home,team_home,driver home,team home
0,2025,Australian Grand Prix,2025-03-16,1,1,1,McLaren,norris,1999-11-13,Albert Park Grand Prix Circuit,Melbourne,AUS,BRI,BRI,0,0
1,2025,Australian Grand Prix,2025-03-16,3,2,1,Red Bull,max_verstappen,1997-09-30,Albert Park Grand Prix Circuit,Melbourne,AUS,DUT,AUT,0,0
2,2025,Australian Grand Prix,2025-03-16,4,3,1,Mercedes,russell,1998-02-15,Albert Park Grand Prix Circuit,Melbourne,AUS,BRI,GER,0,0
3,2025,Australian Grand Prix,2025-03-16,16,4,1,Mercedes,antonelli,NaT,Albert Park Grand Prix Circuit,Melbourne,AUS,NAN,GER,0,0
4,2025,Australian Grand Prix,2025-03-16,6,5,1,Williams,albon,1996-03-23,Albert Park Grand Prix Circuit,Melbourne,AUS,THA,BRI,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,2025,Austrian Grand Prix,2025-06-29,18,16,1,Red Bull,tsunoda,2000-05-11,Red Bull Ring,Spielberg,AUT,JAP,AUT,0,1
234,2025,Austrian Grand Prix,2025-06-29,12,17,3,Williams,albon,1996-03-23,Red Bull Ring,Spielberg,AUT,THA,BRI,0,0
235,2025,Austrian Grand Prix,2025-06-29,7,18,3,Red Bull,max_verstappen,1997-09-30,Red Bull Ring,Spielberg,AUT,DUT,AUT,0,1
236,2025,Austrian Grand Prix,2025-06-29,9,19,3,Mercedes,antonelli,NaT,Red Bull Ring,Spielberg,AUT,NAN,GER,0,0
237,2025,Austrian Grand Prix,2025-06-29,19,20,3,Williams,sainz,1994-09-01,Red Bull Ring,Spielberg,AUT,SPA,BRI,0,0

In [16]:
season2025 = season2025.drop(columns=[ 'driver_home', 'team_home'])
season2025 = season2025.reset_index(drop=True)
season2025

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver home,team home
0,2025,Australian Grand Prix,2025-03-16,1,1,1,McLaren,norris,1999-11-13,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
1,2025,Australian Grand Prix,2025-03-16,3,2,1,Red Bull,max_verstappen,1997-09-30,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
2,2025,Australian Grand Prix,2025-03-16,4,3,1,Mercedes,russell,1998-02-15,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
3,2025,Australian Grand Prix,2025-03-16,16,4,1,Mercedes,antonelli,NaT,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
4,2025,Australian Grand Prix,2025-03-16,6,5,1,Williams,albon,1996-03-23,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,2025,Austrian Grand Prix,2025-06-29,18,16,1,Red Bull,tsunoda,2000-05-11,Red Bull Ring,Spielberg,AUT,0,1
234,2025,Austrian Grand Prix,2025-06-29,12,17,3,Williams,albon,1996-03-23,Red Bull Ring,Spielberg,AUT,0,0
235,2025,Austrian Grand Prix,2025-06-29,7,18,3,Red Bull,max_verstappen,1997-09-30,Red Bull Ring,Spielberg,AUT,0,1
236,2025,Austrian Grand Prix,2025-06-29,9,19,3,Mercedes,antonelli,NaT,Red Bull Ring,Spielberg,AUT,0,0
237,2025,Austrian Grand Prix,2025-06-29,19,20,3,Williams,sainz,1994-09-01,Red Bull Ring,Spielberg,AUT,0,0

In [17]:
season2025.to_csv("season2025_results.csv", index=False)

In [19]:
season2025drivers_with_missing_dob = season2025[season2025['dob'].isna()]
season2025drivers_with_missing_dob

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver home,team home
3,2025,Australian Grand Prix,2025-03-16,16,4,1,Mercedes,antonelli,NaT,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
15,2025,Australian Grand Prix,2025-03-16,15,16,3,Sauber,bortoleto,NaT,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
19,2025,Australian Grand Prix,2025-03-16,11,20,3,RB F1 Team,hadjar,NaT,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
25,2025,Chinese Grand Prix,2025-03-23,8,6,1,Mercedes,antonelli,NaT,Shanghai International Circuit,Shanghai,CHI,0,0
30,2025,Chinese Grand Prix,2025-03-23,7,11,1,RB F1 Team,hadjar,NaT,Shanghai International Circuit,Shanghai,CHI,0,0
33,2025,Chinese Grand Prix,2025-03-23,19,14,1,Sauber,bortoleto,NaT,Shanghai International Circuit,Shanghai,CHI,0,0
45,2025,Japanese Grand Prix,2025-04-06,6,6,1,Mercedes,antonelli,NaT,Suzuka Circuit,Suzuka,JAP,0,0
47,2025,Japanese Grand Prix,2025-04-06,7,8,1,RB F1 Team,hadjar,NaT,Suzuka Circuit,Suzuka,JAP,0,0
58,2025,Japanese Grand Prix,2025-04-06,17,19,1,Sauber,bortoleto,NaT,Suzuka Circuit,Suzuka,JAP,0,0
70,2025,Bahrain Grand Prix,2025-04-13,5,11,1,Mercedes,antonelli,NaT,Bahrain International Circuit,Sakhir,BAH,0,0
72,2025,Bahrain Grand Prix,2025-04-13,12,13,1,RB F1 Team,hadjar,NaT,Bahrain International Circuit,Sakhir,BAH,0,0
77,2025,Bahrain Grand Prix,2025-04-13,18,18,1,Sauber,bortoleto,NaT,Bahrain International Circuit,Sakhir,BAH,0,0
85,2025,Saudi Arabian Grand Prix,2025-04-20,5,6,1,Mercedes,antonelli,NaT,Jeddah Corniche Circuit,Jeddah,SAU,0,0
89,2025,Saudi Arabian Grand Prix,2025-04-20,14,10,1,RB F1 Team,hadjar,NaT,Jeddah Corniche Circuit,Jeddah,SAU,0,0
97,2025,Saudi Arabian Grand Prix,2025-04-20,20,18,1,Sauber,bortoleto,NaT,Jeddah Corniche Circuit,Jeddah,SAU,0,0
105,2025,Miami Grand Prix,2025-05-04,3,6,1,Mercedes,antonelli,NaT,Miami International Autodrome,Miami,AME,0,0
110,2025,Miami Grand Prix,2025-05-04,11,11,1,RB F1 Team,hadjar,NaT,Miami International Autodrome,Miami,AME,0,0
117,2025,Miami Grand Prix,2025-05-04,13,18,3,Sauber,bortoleto,NaT,Miami International Autodrome,Miami,AME,0,0
128,2025,Emilia-Romagna Grand Prix,2025-05-18,9,9,1,RB F1 Team,hadjar,NaT,Autodromo Enzo e Dino Ferrari,Imola,ITA,0,1
137,2025,Emilia-Romagna Grand Prix,2025-05-18,14,18,1,Sauber,bortoleto,NaT,Autodromo Enzo e Dino Ferrari,Imola,ITA,0,0
138,2025,Emilia-Romagna Grand Prix,2025-05-18,13,19,3,Mercedes,antonelli,NaT,Autodromo Enzo e Dino Ferrari,Imola,ITA,0,0
145,2025,Monaco Grand Prix,2025-05-25,5,6,1,RB F1 Team,hadjar,NaT,NaN,Monaco,MON,0,0
153,2025,Monaco Grand Prix,2025-05-25,16,14,1,Sauber,bortoleto,NaT,NaN,Monaco,MON,0,0
157,2025,Monaco Grand Prix,2025-05-25,15,18,1,Mercedes,antonelli,NaT,NaN,Monaco,MON,0,0
172,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,9,7,1,RB F1 Team,hadjar,NaT,Montjuïc,Barcelona,SPA,0,0
173,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,9,7,1,RB F1 Team,hadjar,NaT,Circuit de Pedralbes,Barcelona,SPA,0,0
182,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,12,12,1,Sauber,bortoleto,NaT,Montjuïc,Barcelona,SPA,0,0
183,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,12,12,1,Sauber,bortoleto,NaT,Circuit de Pedralbes,Barcelona,SPA,0,0
194,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,6,18,3,Mercedes,antonelli,NaT,Montjuïc,Barcelona,SPA,0,0
195,2025,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,6,18,3,Mercedes,antonelli,NaT,Circuit de Pedralbes,Barcelona,SPA,0,0
200,2025,Canadian Grand Prix,2025-06-15,4,3,1,Mercedes,antonelli,NaT,NaN,Montréal,CAN,0,0
211,2025,Canadian Grand Prix,2025-06-15,15,14,1,Sauber,bortoleto,NaT,NaN,Montréal,CAN,0,0
213,2025,Canadian Grand Prix,2025-06-15,12,16,1,RB F1 Team,hadjar,NaT,NaN,Montréal,CAN,0,0
225,2025,Austrian Grand Prix,2025-06-29,8,8,1,Sauber,bortoleto,NaT,Red Bull Ring,Spielberg,AUT,0,0
229,2025,Austrian Grand Prix,2025-06-29,13,12,1,RB F1 Team,hadjar,NaT,Red Bull Ring,Spielberg,AUT,0,0
236,2025,Austrian Grand Prix,2025-06-29,9,19,3,Mercedes,antonelli,NaT,Red Bull Ring,Spielberg,AUT,0,0