In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_Formula_One_circuits'
webpage = requests.get(url)
soup = BeautifulSoup(webpage.content, 'lxml')

table = soup.find('table', {'class': 'wikitable sortable'})

In [3]:
headers = [th.get_text(strip=True) for th in table.find_all('th')]

rows = []
for tr in table.find_all('tr')[1:]:
    cells = tr.find_all('td')
    if len(cells) == len(headers):
        row = [cell.get_text(strip=True) for cell in cells]
        rows.append(row)

circuits_df = pd.DataFrame(rows, columns=headers)
circuits_df

,Circuit,Map,Type,Direction,Location,Country,Last length used,Turns,Grands Prix,Season(s),Grands Prix held
0,Adelaide Street Circuit,,Street circuit,Clockwise,Adelaide,Australia,3.780 km (2.349 mi),16,Australian Grand Prix,1985–1995,11
1,Ain-Diab Circuit,,Road circuit,Clockwise,Casablanca,Morocco,7.618 km (4.734 mi),18,Moroccan Grand Prix,1958,1
2,Aintree Motor Racing Circuit,,Road circuit,Clockwise,Aintree,United Kingdom,4.828 km (3.000 mi),12,British Grand Prix,"1955,1957,1959,1961–1962",5
3,Albert Park Circuit*,,Street circuit,Clockwise,Melbourne,Australia,5.278 km (3.280 mi),14,Australian Grand Prix,"1996–2019,2022–2025",28
4,Algarve International Circuit,,Race circuit,Clockwise,Portimão,Portugal,4.653 km (2.891 mi),15,Portuguese Grand Prix,2020–2021,2
...,...,...,...,...,...,...,...,...,...,...,...
73,TI Circuit Aida,,Race circuit,Clockwise,Mimasaka,Japan,3.703 km (2.301 mi),11,Pacific Grand Prix,1994–1995,2
74,Valencia Street Circuit,,Street circuit,Clockwise,Valencia,Spain,5.419 km (3.367 mi),25,European Grand Prix,2008–2012,5
75,Watkins Glen International,,Race circuit,Clockwise,Watkins Glen,United States,5.430 km (3.374 mi),10,United States Grand Prix,1961–1980,20
76,Yas Marina Circuit*,,Race circuit,Anti-clockwise,Abu Dhabi,United Arab Emirates,5.281 km (3.281 mi),15,Abu Dhabi Grand Prix,2009–2024,16
77,Zeltweg Airfield,,Road circuit,Clockwise,Zeltweg,Austria,3.186 km (1.980 mi),4,Austrian Grand Prix,1964,1

In [4]:
circuits_df['Circuit'] = circuits_df['Circuit'].str.replace('*', '', regex=False).str.strip()
circuits_df['Circuit'] = circuits_df['Circuit'].replace({
    'Albert Park Circuit': 'Albert Park Grand Prix Circuit',
    'Suzuka International Racing Course': 'Suzuka Circuit',
    'Circuit de Spa-Francorchamps': 'Circuit de Spa-Francorchamps',
    'Autodromo Internazionale Enzo e Dino Ferrari': 'Autodromo Enzo e Dino Ferrari',
    'Autodromo José Carlos Pace': 'Autódromo José Carlos Pace',
    'Autodromo Nazionale di Monza': 'Autodromo Nazionale di Monza',
    'Circuit Gilles-Villeneuve': 'Circuit Gilles Villeneuve',
    'Circuit Zandvoort': 'Circuit Park Zandvoort',
    'Las Vegas Strip Circuit': 'Las Vegas Strip Street Circuit',
    'Lusail International Circuit': 'Losail International Circuit',
    'Suzuka International Racing Course': 'Suzuka Circuit',
})

In [5]:
circuits_df.rename(columns={
    'Circuit': 'circuit name'}, inplace=True)

In [6]:
circuits_df

,circuit name,Map,Type,Direction,Location,Country,Last length used,Turns,Grands Prix,Season(s),Grands Prix held
0,Adelaide Street Circuit,,Street circuit,Clockwise,Adelaide,Australia,3.780 km (2.349 mi),16,Australian Grand Prix,1985–1995,11
1,Ain-Diab Circuit,,Road circuit,Clockwise,Casablanca,Morocco,7.618 km (4.734 mi),18,Moroccan Grand Prix,1958,1
2,Aintree Motor Racing Circuit,,Road circuit,Clockwise,Aintree,United Kingdom,4.828 km (3.000 mi),12,British Grand Prix,"1955,1957,1959,1961–1962",5
3,Albert Park Grand Prix Circuit,,Street circuit,Clockwise,Melbourne,Australia,5.278 km (3.280 mi),14,Australian Grand Prix,"1996–2019,2022–2025",28
4,Algarve International Circuit,,Race circuit,Clockwise,Portimão,Portugal,4.653 km (2.891 mi),15,Portuguese Grand Prix,2020–2021,2
...,...,...,...,...,...,...,...,...,...,...,...
73,TI Circuit Aida,,Race circuit,Clockwise,Mimasaka,Japan,3.703 km (2.301 mi),11,Pacific Grand Prix,1994–1995,2
74,Valencia Street Circuit,,Street circuit,Clockwise,Valencia,Spain,5.419 km (3.367 mi),25,European Grand Prix,2008–2012,5
75,Watkins Glen International,,Race circuit,Clockwise,Watkins Glen,United States,5.430 km (3.374 mi),10,United States Grand Prix,1961–1980,20
76,Yas Marina Circuit,,Race circuit,Anti-clockwise,Abu Dhabi,United Arab Emirates,5.281 km (3.281 mi),15,Abu Dhabi Grand Prix,2009–2024,16
77,Zeltweg Airfield,,Road circuit,Clockwise,Zeltweg,Austria,3.186 km (1.980 mi),4,Austrian Grand Prix,1964,1

In [7]:
circuits_df.to_csv('circuits_df.csv', index=False)